// generate-qr.js - Standalone QR code generator
const QRCode = require('qrcode');
const fs = require('fs');
const path = require('path');
const { Builder } = require('xml2js');

async function generateQRCodes() {
  // Get input from environment variables or command line args
  const uniqueIdsInput = process.env.UNIQUE_IDS || process.argv[2] || 'featured-products,contact,about';
  const batchName = process.env.BATCH_NAME || process.argv[3] || 'qr-batch';
  
  const uniqueIds = uniqueIdsInput.split(',').map(id => id.trim());
  const timestamp = new Date().toISOString();
  
  console.log(`🚀 Starting QR code generation for Local Bar Tees`);
  console.log(`📦 Batch: ${batchName}`);
  console.log(`🔢 IDs: ${uniqueIds.join(', ')}`);
  
  // Create output directory (write directly to qr folder)
  const outputDir = `qr`;
  
  fs.mkdirSync(outputDir, { recursive: true });
  
  const qrData = [];
  
  for (const uniqueId of uniqueIds) {
    try {
      // Construct URL with ?qr parameter
      const cleanId = uniqueId.replace(/^\/+/, '');
      const fullUrl = `https://locabartees.com/${cleanId}?qr`;
      
      // Generate QR code PNG directly in qr directory
      const filename = `locabartees-qr-${cleanId.replace(/[^a-zA-Z0-9-]/g, '-')}.png`;
      const pngPath = path.join(outputDir, filename);
      
      await QRCode.toFile(pngPath, fullUrl, {
        width: 300,
        height: 300,
        margin: 2,
        color: {
          dark: '#2d3748',  // Dark gray
          light: '#ffffff'  // White
        },
        errorCorrectionLevel: 'M'  // Medium error correction
      });
      
      // Collect data for XML
      const qrInfo = {
        uniqueId: cleanId,
        url: fullUrl,
        filename: filename,
        generated: timestamp,
        size: '300x300',
        errorCorrection: 'M',
        fileSize: fs.statSync(pngPath).size
      };
      
      qrData.push(qrInfo);
      
      console.log(`✅ Generated: ${uniqueId} → ${filename}`);
      
    } catch (error) {
      console.error(`❌ Failed to generate QR code for ${uniqueId}:`, error.message);
    }
  }
  
  // Generate qr.xml file in qr directory
  const xmlData = {
    qrCodes: {
      $: { 
        version: '1.0',
        generator: 'Local Bar Tees QR Generator',
        batchName: batchName,
        generated: timestamp,
        count: qrData.length
      },
      summary: {
        totalFiles: qrData.length + 1, // PNG files + XML file
        totalSize: qrData.reduce((sum, item) => sum + item.fileSize, 0),
        baseUrl: 'https://locabartees.com',
        qrParameter: '?qr'
      },
      codes: {
        code: qrData.map(item => ({
          $: { uniqueId: item.uniqueId },
          url: item.url,
          filename: item.filename,
          size: item.size,
          errorCorrection: item.errorCorrection,
          fileSizeBytes: item.fileSize,
          generated: item.generated
        }))
      }
    }
  };
  
  const builder = new Builder({
    xmldec: { version: '1.0', encoding: 'UTF-8' },
    pretty: true
  });
  const xml = builder.buildObject(xmlData);
  
  const xmlPath = path.join(outputDir, 'qr.xml');
  fs.writeFileSync(xmlPath, xml);
  
  // Generate README
  const readmePath = path.join(outputDir, 'README.md');
  const totalSize = qrData.reduce((sum, item) => sum + item.fileSize, 0);
  const readmeContent = `# Local Bar Tees QR Code Batch: ${batchName}

**Generated:** ${new Date(timestamp).toLocaleString()}  
**Total QR Codes:** ${qrData.length}  
**Total File Size:** ${(totalSize / 1024).toFixed(2)} KB  

## 📁 Directory Structure
\`\`\`
qr/
├── locabartees-qr-shirt-123.png    # QR code images (300x300 PNG)
├── locabartees-qr-promo-summer.png
├── locabartees-qr-contact.png
├── qr.xml                          # All QR code metadata
└── README.md                       # This file
\`\`\`

## 🔗 Generated QR Codes

| Unique ID | URL | Filename |
|-----------|-----|----------|
${qrData.map(item => `| \`${item.uniqueId}\` | ${item.url} | ${item.filename} |`).join('\n')}

## 📱 Usage Instructions

1. **For Print/Digital Use:** Use PNG files directly from this directory
2. **For Integration/Tracking:** Use \`qr.xml\` for all metadata
3. **Simple Access:** Everything in one qr/ folder

## ⚙️ Technical Specifications

- **Size:** 300x300 pixels
- **Format:** PNG with transparency support
- **Error Correction:** Medium (M) - 15% damage recovery
- **Colors:** Dark gray (#2d3748) on white (#ffffff)
- **URL Parameter:** All URLs include \`?qr\` for tracking

## 🔄 Regeneration

To regenerate this batch, run:
\`\`\`bash
node generate-qr.js "${uniqueIds.join(',')}" "${batchName}"
\`\`\`

---
*Generated by Local Bar Tees QR Generator*
`;
  
  fs.writeFileSync(readmePath, readmeContent);
  
  // Summary output
  console.log(`\n🎉 Batch generation complete!`);
  console.log(`📁 Output directory: ${outputDir}`);
  console.log(`📊 Generated: ${qrData.length} QR codes`);
  console.log(`📄 Files created: ${qrData.length} PNGs, 1 XML, 1 README`);
  console.log(`💾 Total size: ${(totalSize / 1024).toFixed(2)} KB`);
  
  return {
    outputDir,
    count: qrData.length,
    totalSize
  };
}

// Run if called directly
if (require.main === module) {
  generateQRCodes().catch(error => {
    console.error('❌ Generation failed:', error);
    process.exit(1);
  });
}

module.exports = { generateQRCodes };