name: Add QR Code
on:
  workflow_dispatch:
    inputs:
      bar_name:
        description: 'Bar/Band Name'
        required: true
        type: string
      qr_id:
        description: 'QR Code ID (web shop stem)'
        required: true
        type: string

jobs:
  add-qr-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Show current XML
        run: |
          echo "Current XML file:"
          cat assets/qr.xml
          
      - name: Add new QR entry to XML
        run: |
          BAR_NAME="${{ github.event.inputs.bar_name }}"
          QR_ID="${{ github.event.inputs.qr_id }}"
          WEBSITE_URL="https://localbartees.com/${QR_ID}"
          
          echo "Adding QR code:"
          echo "  Bar/Band: ${BAR_NAME}"
          echo "  QR ID: ${QR_ID}"
          echo "  URL: ${WEBSITE_URL}"
          
          # Create the new entry in a temporary file
          cat > new_entry.xml << EOF
  <qr ${QR_ID}="${QR_ID}">
    <name>${BAR_NAME}</name>
    <url>${WEBSITE_URL}</url>
  </qr>
EOF
          
          # Remove the last line (</root>) from the original file
          head -n -1 assets/qr.xml > temp.xml
          
          # Add our new entry
          cat new_entry.xml >> temp.xml
          
          # Add the closing </root> tag back
          echo "</root>" >> temp.xml
          
          # Replace the original file
          mv temp.xml assets/qr.xml
          
          # Clean up
          rm new_entry.xml
          
      - name: Show updated XML
        run: |
          echo "Updated XML file:"
          cat assets/qr.xml
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/qr.xml
          git commit -m "Add QR code for ${{ github.event.inputs.bar_name }}"
          git push