name: Add QR Code
on:
  workflow_dispatch:
    inputs:
      bar_name:
        description: 'Bar/Band Name'
        required: true
        type: string
      qr_id:
        description: 'QR Code ID'
        required: true
        type: string

jobs:
  add-qr-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Add QR Code
        run: |
          echo "Bar/Band Name: ${{ github.event.inputs.bar_name }}"
          echo "QR ID: ${{ github.event.inputs.qr_id }}"
          
          # Read current XML
          cat assets/qr.xml
          
          # Create new entry
          cat >> temp_entry.txt << EOF
  <qr ${{ github.event.inputs.qr_id }}="${{ github.event.inputs.qr_id }}">
    <name>${{ github.event.inputs.bar_name }}</name>
    <url>https://localbartees.com/${{ github.event.inputs.qr_id }}</url>
  </qr>
EOF
          
          # Insert before </root>
          head -n -1 assets/qr.xml > temp.xml
          cat temp_entry.txt >> temp.xml
          echo "</root>" >> temp.xml
          mv temp.xml assets/qr.xml
          
          # Clean up
          rm temp_entry.txt
          
          echo "New XML:"
          cat assets/qr.xml
          
      - name: Commit
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add assets/qr.xml
          git commit -m "Add ${{ github.event.inputs.bar_name }}"
          git push