name: Add QR Code
on:
  workflow_dispatch:
    inputs:
      bar_name:
        description: 'Bar/Band Name'
        required: true
        type: string
      qr_id:
        description: 'QR Code ID (web shop stem)'
        required: true
        type: string

jobs:
  add-qr-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Add new QR entry to XML
        run: |
          BAR_NAME="${{ inputs.bar_name }}"
          QR_ID="${{ inputs.qr_id }}"
          WEBSITE_URL="https://localbartees.com/${QR_ID}"
          
          echo "Adding QR code:"
          echo "  Bar/Band: ${BAR_NAME}"
          echo "  QR ID: ${QR_ID}" 
          echo "  URL: ${WEBSITE_URL}"
          
          # Create the new QR entry
          NEW_ENTRY="  <qr ${QR_ID}=\"${QR_ID}\">
    <name>${BAR_NAME}</name>
    <url>${WEBSITE_URL}</url>
  </qr>"
          
          # Insert before </root> using sed
          sed -i "/<\/root>/i\\${NEW_ENTRY}" assets/qr.xml
          
      - name: Show updated XML
        run: |
          echo "Updated XML file:"
          cat assets/qr.xml
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/qr.xml
          git commit -m "Add QR code for ${{ inputs.bar_name }}"
          git push